@startuml test document number 2

actor a as "Judy"
actor b as "James"

note right of a :::: This is a note
a -> b : Hi James, how are you?
b --> a : All good! And you?
a -> b : Thank you, I'm fine! One question: do you know a good operating system?
b --> a : MacOS is great! I'm using it all the time!
a -> b : Good to know, thanks. Do you also use Windows or Linux?
b --> a : Yes, my partner uses Windows on their machine. It works well.
a -> b : Okay, thanks! See you later!
b --> a : Bye!

@enduml
