@startuml test document number 1

actor a as "Alice"
actor b as "Bob"

a -> b : Hi Bob, how are you?
b --> a : I'm fine, thanks! How are you?
a -> b : Great, thanks! Do you have a recommendation for an operating system?
b --> a : Sure! Personally I prefer Linux, but I understand some have a preference for MacOS.
a -> b : Thank you! How about Windows?
b --> a : Hell no.
a -> b : Sure, that's all. See you!
b --> a : Goodbye!

@enduml
