@startuml

' parts of the example taken from the PlantUML page: https://plantuml.com/class-diagram#a339d3559f33ad64

abstract class AbstractList
abstract AbstractCollection
interface List
interface Collection

List <|-- AbstractList
Collection <|-- AbstractCollection

Collection <|- List
AbstractCollection <|- AbstractList
AbstractList <|-- ArrayList

class ArrayList {
  Object[] elementData
  size()
}

@enduml
