@startuml

node node {
  cloud cloud
  artifact artifact
  collections collections
  database database
  queue queue

  cloud -- artifact : label1
  cloud .. collections : label2
  cloud ~~ database : label3
  cloud == queue
}

@enduml
