@startuml oauth2-protocol-flow

participant Client as c
participant "Resource Owner" as ro
participant "Authorization Server" as as
participant "Resource Server" as rs

c -> ro : (1) Authorization Request
ro --> c : (2) Authorization Grant

c -> as : (3) Authorization Grant
as --> c : (4) Access Token

c -> rs : (5) Access Token
rs --> c : (6) Protected Resource

@enduml
