@startuml oauth2-client-credentials-flow

participant Client as c
participant "Authorization Server" as as
participant "Resource Server" as rs

c -> as : client authentication
as --> c : access token

c -> rs : access token
rs --> c : protected resource

@enduml
