@startuml oauth2-refresh-token-flow

participant Client as c
participant "Authorization Server" as as
participant "Resource Server" as rs

c -> as : authorization grant
as --> c : access token & refresh token

c -> rs : access token
rs --> c : protected resource
c -> rs : access token
rs --> c : invalid token error

c -> as : refresh token
as --> c : access token & optional refresh token

@enduml
