@startuml oauth2-token-exchange-flow

participant Client as c
participant "Authorization Server" as as
participant "Resource Server" as rs

c -> as : subject token
as --> c : access token

c -> rs : access token
rs --> c : protected resource

@enduml
