@startuml oauth2-authorization-code-flow

participant Client as c
participant "Authorization Server" as as
participant "Resource Server" as rs

c -> as : redirect to /authorize endpoint
as --> c : login page

c -> as : log in
as -> as : validate credentials
as --> c : show grant page
c -> as : grant access
as --> c: authorization code
c -> as : authorization code and redirection URI
as --> c : access token (with optional refresh token)

c -> rs : access token
rs --> c : protected resource

@enduml
