@startuml example-sequence

actor Alice
actor Eve
actor Bob

Alice -> Bob : Hi Bob!
Bob --> Alice : Hello Alice!

...

Alice -> Eve : I think someone is spying\non our conversation
Eve -> Bob : Nice weather today, isn't it?
Bob --> Eve : It surely is!
Eve --> Alice : Nah, I don't think so...

@enduml
