@startuml lsp-gpt arch

skinparam Linetype ortho

package "host machine" {

  package "ide" as ide {
      [Language Client]
  }

  folder files
  folder configuration
  
  [lsp-gpt]
}

cloud remote {
    [GPT API]
}

ide --> files
[lsp-gpt] --> configuration
[lsp-gpt] --> files

[Language Client] --> [lsp-gpt] : request
[lsp-gpt] -> [GPT API] : prompted request

@enduml
