@startuml lsp-gpt-diagnostics

box editor
participant lc as "language client"
end box
participant ls as "language server"
box openAI
participant gpt as "GPT API"
end box

== request - response ==

lc -> ls : request for code completion
ls -> gpt : forward request with prompt
gpt --> ls : response
ls --> lc : response

== language client notifications ==

lc -> ls : document opened/changed/saved

== language server notifications ==

ls -> gpt : request with prompt
gpt --> ls : response as notification
ls --> lc : notification

@enduml
